# Minimal Dolos config for Preprod (example)
# NOTE: You must provide the genesis JSON files referenced below.

[upstream]
peer_address = "preprod-node.world.dev.cardano.org:30000"
network_magic = 1
is_testnet = true

[storage]
version = "v1"
path = "/data"
max_wal_history = 10000
max_chain_history = 10000

[genesis]
byron_path = "/config/genesis/byron.json"
shelley_path = "/config/genesis/shelley.json"
alonzo_path = "/config/genesis/alonzo.json"
conway_path = "/config/genesis/conway.json"

[chain]
type = "Cardano"

[chain.track]
seen_addresses = true
asset_state = true
pool_state = true
pool_delegator = true
epoch_state = true
account_activity = true
reward_logs = true

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[logging]
max_level = "info"
include_tokio = false
include_pallas = false
