name: Backend CI

on:
  push:
    paths:
      - "apps/api/**"
      - "packages/shared/**"
      - "turbo.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - "apps/api/**"
      - "packages/shared/**"
      - "turbo.json"
      - "pnpm-lock.yaml"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    concurrency:
      group: backend-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run unit tests (api)
        run: pnpm --filter api test -- --ci
        env:
          CI: true
      - name: Typecheck API (build)
        run: pnpm --filter api build
